### ISSUE TITLE
Cloudformation S3 error - Access Denied

### ISSUE THREAD

**Issue by extern-mathias-pancrate** [aws-ia/cfn-ps-cisco-meraki-vmx-cloudwan#16]
Hello,
When we deploy this quickstart we have an error when cloudformation run deployment of "VMX1Stack" and "VMX2Stack":
-----
S3 error: Access Denied For more information check http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html
-----

We left the default settings (QSS3BucketName, QSS3BucketRegion, and QSS3KeyPrefix),as describe here: https://aws-ia.github.io/cfn-ps-cisco-meraki-vmx-cloudwan/#_deployment_steps

Is there an access problem on the S3 bucket ?

Regards,

Mathias.

**Comment by vsnyc** [comment]
The issue was caused due to a missing submodule, and has been fixed in commit: https://github.com/aws-ia/cfn-ps-cisco-meraki-vmx-cloudwan/pull/15/commits/0e8055cfecd65bbf5c79de225facc8e66b033ad7
